services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL="YOUR_SUPABASE_URL"
      - NEXT_PUBLIC_SUPABASE_ANON_KEY="YOUR_SUPABASE_ANON_KEY"
    restart: unless-stopped
    networks:
      - byos_network


networks:
  byos_network:
    driver: bridge
